### ISSUE TITLE
Tis a message to Sir Gavin.

### ISSUE THREAD

**Issue by MeLike2D** [Stereo-Developers/issues#2]
It has come to great amazement that stereo is great, "but Sir 2D, stereo is a great bot. Tis not a lie!" my maid said before I banished  her from my home! Now I realize, she was no liar. But a mesiah.

**Comment by Sxmurai** [comment]
what in the big anime tiddie fuck is this

**Comment by MeLike2D** [comment]
What foolery is this!

**Comment by MeLike2D** [comment]
How dare you close thee issue of Sir 2D !

**Comment by MeLike2D** [comment]
I have you know I graduated top of my class within oxford.

**Comment by MeLike2D** [comment]
You should be ashamed of your actions! You will regret this Sir Gavin!

**Comment by Sxmurai** [comment]
what in the mcdonalds happy meal flip phone disowned ice cream cone shit is this

**Comment by MeLike2D** [comment]
HOW DARE YOU SWEAR IN MY HOUSEHOLD!!!!?!???!!??!?!#

**Comment by Sxmurai** [comment]
cunt

**Comment by MeLike2D** [comment]
*Gasps*

**Comment by Sxmurai** [comment]
you needa get urself some stardust LEDs

**Comment by MeLike2D** [comment]
WITCH! TIS A WITCH

**Comment by Sxmurai** [comment]
no no, you need some Gfuel using code SOG at checkout

**Comment by MeLike2D** [comment]
ONLY WITCHES KNOW THE FUTURE.

**Comment by MeLike2D** [comment]
Wait..

**Comment by MeLike2D** [comment]
I do not know the future, tis only a guess

**Comment by Sxmurai** [comment]
so by your nickname, do you like 2 dimensional girls? you know, like anime/hentai

**Comment by MeLike2D** [comment]
Of course not!! I do not sin, faithful I am to God.

**Comment by Sxmurai** [comment]
so does that mean cumming is a sin, cause that means i sin every other day

**Comment by MeLike2D** [comment]
Sinner!!!!!!

**Comment by Sxmurai** [comment]
mate i just admitted to it

**Comment by Sxmurai** [comment]
is it true that you only are allowed to do missionary while having sex, must be boring
